# permissions for end users to view mssqlservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mssqlserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devdb-operator
    app.kubernetes.io/part-of: devdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mssqlserver-viewer-role
rules:
- apiGroups:
  - devdb.io
  resources:
  - mssqlservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devdb.io
  resources:
  - mssqlservers/status
  verbs:
  - get
