# permissions for end users to view mssqldatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mssqldatabase-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devdb-operator
    app.kubernetes.io/part-of: devdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: mssqldatabase-viewer-role
rules:
- apiGroups:
  - devdb.io
  resources:
  - mssqldatabases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devdb.io
  resources:
  - mssqldatabases/status
  verbs:
  - get
